# Generated by Django 4.2 on 2025-05-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du site')),
                ('description', models.TextField(verbose_name='Description')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('about', models.TextField(verbose_name='À propos du club')),
            ],
        ),
    ]
