# Generated by Django 4.2 on 2025-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tc_casabona_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'article")),
                ('description', models.TextField(verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date de publication')),
                ('feature_image', models.ImageField(upload_to='blog_images/', verbose_name="Image de l'article")),
                ('tags', models.CharField(max_length=255, verbose_name='Tags (séparés par des virgules)')),
                ('content', models.TextField(verbose_name="Contenu de l'article")),
            ],
        ),
    ]
